[package]
name = "minilua"
version = "0.1.0"
edition = "2021"
description = "A pedagogical lab for learning general compilation principles."
authors = ["Aloïs Rautureau <alois.rautureau@ens-rennes.fr>", "Paul Adam <paul.adam@ens-rennes.fr>"]
license = "Unlicense"

[dependencies]
